#ifndef GAME_SETTINGS_H_INCLUDED
#define GAME_SETTINGS_H_INCLUDED

#define XMAX 80
#define YMAX 25

#define SHOT_DELAY 18
#define PLAYER_SPEED 4
//Delay enemies movements
#define ENEMY_SPEED 2
#define ENEMY_SPEED_DIF 3
#define ENEMY_REACTION_TIME 10
#define DECTECTION_RANGE 25
#define START_DEATH_STAGE 3
#define DEATH_SPEED 20

#define BUFFER 5

#define LEVEL_MOD 5
#define LEVELS_TO_WIN 1

#define REFRESH 33

#endif // GAME_SETTINGS_H_INCLUDED
